Vizzuality/waterbird-population

README.md

Readme update to add Icons and env variables management

readme update (icomoon and now)

---

src/components/data-detail/component.js
src/components/data-detail/templates/conservation-framework/component.js
src/components/populations-card/component.js
src/components/species-data/component.js
src/components/species-data/index.js
src/modules/map/reducers.js
src/modules/population/actions.js
src/modules/population/initial-state.js
src/modules/population/reducers.js
src/services/population.js

WIP: fetch populations + redux

WIP: populationns in redux

---

src/components/download/component.js
src/services/population.js

- Conservation framework data added to populations query

conservation framework query

---

src/components/data-detail/comments/component.js
src/components/data-detail/comments/index.js
src/components/data-detail/component.js
src/components/data-detail/index.js
src/components/data-detail/templates/population-percent/component.js
src/components/data-detail/templates/population-size/component.js
src/components/data-detail/templates/population-trend/component.js
src/components/data-detail/templates/population-trend/styles.scss
src/modules/population/selectors.js
src/pages/explore/detail/component.js
src/pages/explore/detail/index.js
src/services/comments.js
src/services/conservation.js
src/services/families.js
src/services/flyways.js
src/services/population.js
src/services/publications.js
src/services/red-list.js
src/services/species.js
src/services/users.js

This PR adds: 
- encodeURIcomponent to all services
- specific ids to all comments depending on the area commented

comments with specific ids

---

package.json
src/components/data-controls/component.js
src/components/family-list/index.js
src/components/filters/component.js
src/components/home/section1/constants.js
src/components/search/component.js
src/components/search/index.js
src/components/species-list/component.js
src/components/species-list/index.js
src/modules/population/actions.js
src/modules/population/initial-state.js
src/modules/population/reducers.js
src/modules/population/selectors.js
src/pages/explore/overview/component.js
yarn.lock

EXPLORE page:
- Search functionality added
- Filters Select fixed

filters select fix, search functionality added in EXPLORE

---

src/components/data-detail/comments/component.js
src/components/data-detail/component.js
src/components/data-detail/templates/conservation-framework/component.js
src/components/data-detail/templates/conservation-framework/constants.js
src/components/data-detail/templates/population-info/component.js
src/components/data-detail/templates/population-percent/component.js
src/components/data-detail/templates/population-size/component.js
src/components/data-detail/templates/population-trend/component.js
src/components/filters/component.js
src/components/home/section1/component.js
src/components/home/section1/index.js
src/components/home/section1/styles.scss
src/components/populations-list/component.js
src/components/species-list-item/component.js
src/components/species-list-item/index.js
src/modules/population/constants.js
src/modules/population/selectors.js
src/services/images.js
src/services/population.js
src/services/red-list.js
src/services/users.js

- Conservation framework added to query and EXPLORE DETAIL page.
- New query to fetch populations pointing to new view created in CARTO.
- Color tags added for red list categories tags.
- Links to EXPLORE DETAIL with filters added in landing page.
- Species row all clickable
- Hide just textarea in publicated comments instead of all comment (just logged users view)
- Temporal fix in search. Eventually all filters will be arrays and there won't be need for conditions of data type in selectPopulationFiltered
- Bug fixed in filters selected option (EXPLORE OVERVIEW page)

conservation framework part

---

src/components/data-detail/templates/population-percent/component.js
src/components/data-detail/templates/population-size/component.js
src/components/data-detail/templates/population-trend/component.js
src/modules/population/selectors.js

Fix notes pop up
Token to env variable

fix: notes tooltip

---

src/pages/explore/detail/map/component.js
src/pages/explore/overview/map/component.js

This PR hides legend in both maps as current legend is not accurate with results on map

map legend hidden

---

src/components/data-detail/component.js
src/modules/population/selectors.js

console.log

---

src/components/data-detail/styles.scss
src/components/data-detail/templates/conservation-framework/component.js
src/components/data-detail/templates/population-percent/component.js
src/components/data-detail/templates/population-size/component.js
src/components/data-detail/templates/population-trend/component.js

EXPLORE DETAIL page: border highlighted in table when selecting a comment

EXPLORE DETAIL: highlighted comment when active

---

src/components/analysis/component.js
src/components/analysis/index.js
src/components/data-controls/component.js
src/components/data-controls/index.js
src/components/populations-list/component.js
src/modules/analysis/selectors.js
src/modules/population/selectors.js
src/pages/explore/overview/component.js
src/pages/explore/overview/index.js
src/services/population.js

Feature added to download data from widgets

widgets data to download

---

src/components/populations-list/component.js

Bug fixed in explore overview, card linked to detail

bug: card linked to detail

---

src/components/analysis/filters/active-filters/component.js
src/components/analysis/filters/clear-filters/component.js
src/components/analysis/filters/clear-filters/index.js
src/components/analysis/filters/clear-filters/styles.scss
src/components/analysis/filters/component.js
src/components/analysis/filters/index.js
src/components/data-controls/component.js
src/components/download/styles.scss
src/components/filters/active-filters/component.js
src/components/filters/clear-filters/styles.scss
src/components/filters/component.js
src/components/filters/styles.scss
src/components/map/legend/component.js
src/components/map/legend/styles.scss
src/modules/analysis/actions.js
src/modules/analysis/reducers.js
src/modules/analysis/selectors.js
src/modules/explore/selectors.js
src/modules/user/reducers.js

- Log out bug fixed
- Explore filters removed from analysis

log out bug, filters styles

---

src/components/map/legend/component.js
src/components/map/legend/styles.scss
src/modules/analysis/selectors.js

New wrapper added to map legend

legend wrapper

---

package.json
src/components/download/component.js
src/components/download/styles.scss
src/components/filters/active-filters/component.js
src/components/populations-list/component.js
src/utils/csv.js
yarn.lock

Fix download button. It was rendering no data at first. Race condition
- Add spinner (Global download is very slow)
- Async download
- Use a different library (wasn't supporting async)
- Fix titles for filtered downloads

Download async - WIP

---

src/modules/explore/selectors.js

prevent population overview to crash when there is no population selected

fix bug when no publication selected

---

src/components/data-detail/templates/population-info/component.js
src/components/download/styles.scss
src/components/header/component.js
src/modules/explore/selectors.js
src/pages/explore/detail/map/populations-selector/component.js
src/pages/explore/detail/map/populations-selector/styles.scss

- EXPLORE DETAIL: default option set in population select in map, tag colors fixed

tag color in explore detail, header in mobile

---

src/components/data-detail/templates/references/component.js
src/modules/explore/selectors.js
src/pages/downloads/constants/downloads.js

- EXPLORE DETAIL: removed distinction between trend and size references to avoid duplicated when reference belongs to both
- Download link static page modified

references and download links modified

---

src/components/analysis/widget-templates/estimates/config.js
src/components/analysis/widget-templates/families/config.js
src/components/analysis/widget-templates/populations/config.js
src/components/data-detail/component.js
src/components/data-detail/templates/population-percent/component.js
src/components/data-detail/templates/population-size/component.js
src/components/data-detail/templates/population-trend/component.js
src/components/map/component.js
src/components/map/index.js
src/components/map/styles.scss
src/components/recharts/component.js
src/components/species-list-item/component.js
src/modules/analysis/selectors.js
src/modules/explore/selectors.js
src/pages/explore/detail/component.js
src/pages/explore/detail/index.js
src/pages/explore/detail/map/component.js

This PR: 
- Fixes a bug for map print preview in firefox.
- Changes labels in widgets.
- Force all info to be expanded in Explore detail when a publication is selected.

prinnt map bug, search adjust, new labels in charts

---

src/components/data-detail/templates/population-info/component.js
src/components/data-detail/templates/population-info/styles.scss
src/components/data-detail/templates/specie-info/component.js
src/components/data-detail/templates/specie-info/styles.scss
src/pages/explore/detail/map/populations-selector/component.js
src/pages/explore/detail/map/populations-selector/styles.scss

Change text colors in labels to improve visibility

tag colors

---

src/components/header/styles.scss
src/components/nav-menu/constants.js
src/pages/explore/styles.scss

padding title pdf

---

.nvmrc
src/components/footer/styles.scss
src/pages/explore/detail/component.js

typo in map, media print footer

---

src/components/data-detail/templates/notes/styles.scss
src/components/data-detail/templates/references/styles.scss
src/components/footer/styles.scss
src/services/population.js
src/styles/_base.scss

card query update

---

src/services/population.js

all publications download

---

src/components/data-controls/component.js
src/components/data-controls/styles.scss
src/components/download/component.js
src/services/population.js

Change analyze download to "go to downloads" link

analyze button

---

src/components/analysis/component.js
src/components/card/component.js
src/components/card/styles.scss
src/components/filters/component.js
src/components/tabs-menu/component.js
src/components/tabs-menu/styles.scss
src/components/user-signin/register/component.js
src/pages/about/constants/contact.js
src/pages/about/constants/info.js
src/pages/about/constants/terms.js
src/pages/background/constants/conservation-framework.js
src/pages/background/constants/waf.js
src/pages/background/constants/wiwp.js
src/pages/credits/constants/ec.js
src/pages/credits/constants/fs.js
src/pages/data/constants/s&p.js
src/pages/downloads/constants/downloads.js
src/pages/explore/overview/map/component.js
src/pages/static-page/index.js

Wetlands international wetlands final changes

---

src/components/filters/component.js
src/components/user-signin/register/component.js
src/pages/about/constants/contact.js
src/pages/about/constants/info.js
src/pages/about/constants/terms.js
src/pages/background/constants/waf.js
src/pages/credits/constants/ec.js
src/pages/credits/constants/fs.js
src/pages/data/constants/s&p.js
src/pages/downloads/constants/downloads.js
src/pages/explore/overview/map/component.js

Updated number of static pages, fixed the links of the info buttons on the Advanced Filter, fixed contact email, fix typo's
Please check the following:
- static pages for proper display of content
- the info buttons on the advanced filter (now use hyperlink or anchors to other WPP pages)

Update static pages, info buttons

---

src/components/card/styles.scss
src/components/data-detail/templates/conservation-framework/component.js
src/components/filters/component.js
src/components/home/section1/component.js
src/components/home/section1/constants.js
src/components/home/section3/component.js
src/components/search/component.js
src/components/tabs-menu/component.js
src/components/tabs-menu/styles.scss
src/pages/background/constants/waw.js
src/pages/constants.js
src/pages/credits/constants/fs.js
src/pages/data/constants/s&p.js
src/services/references.js

link updates
